In [3]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in /home/arcane/Desktop/Python/Notebooks/.venv/lib/python3.13/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /home/arcane/Desktop/Python/Notebooks/.venv/lib/python3.13/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/arcane/Desktop/Python/Notebooks/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/arcane/Desktop/Python/Notebooks/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("./archive/corporate_ai_adoption_dataset.csv")

In [6]:
df.head()

,company_id,industry,country,year,ai_adoption_level,ai_investment_usd,automation_rate,cost_savings,revenue_impact,productivity_gain,employee_ai_training_hours,ai_maturity_score,deployment_count
0,CORP-06613,Financial Services,China,2029,0.4987,11747237,0.4119,3519354,2751513,0.3924,76.8,6.37,29
1,CORP-01597,Agriculture,Germany,2032,0.5213,1267219,0.4580,295244,304776,0.4639,83.2,7.19,37
2,CORP-02938,Energy,United States,2024,0.6147,8168951,0.5821,2472329,5170304,0.4953,123.1,6.72,26
3,CORP-05207,Retail,Germany,2021,0.4401,1234261,0.2880,512061,-233448,0.3078,63.1,5.68,21
4,CORP-07489,Technology,United States,2024,0.1918,5000645,0.1906,2122064,2110644,0.1910,29.6,4.33,16

In [7]:
df.isnull().sum()

company_id                    0
industry                      0
country                       0
year                          0
ai_adoption_level             0
ai_investment_usd             0
automation_rate               0
cost_savings                  0
revenue_impact                0
productivity_gain             0
employee_ai_training_hours    0
ai_maturity_score             0
deployment_count              0
dtype: int64

In [8]:
df.shape

(200000, 13)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   company_id                  200000 non-null  str
 1   industry                    200000 non-null  str
 2   country                     200000 non-null  str
 3   year                        200000 non-null  int64
 4   ai_adoption_level           200000 non-null  float64
 5   ai_investment_usd           200000 non-null  int64
 6   automation_rate             200000 non-null  float64
 7   cost_savings                200000 non-null  int64
 8   revenue_impact              200000 non-null  int64
 9   productivity_gain           200000 non-null  float64
 10  employee_ai_training_hours  200000 non-null  float64
 11  ai_maturity_score           200000 non-null  float64
 12  deployment_count            200000 non-null  int64
dtypes: float64(5), int64(5), str(3)
memory usage: 19.8 MB

In [10]:
df.columns

Index(['company_id', 'industry', 'country', 'year', 'ai_adoption_level',
       'ai_investment_usd', 'automation_rate', 'cost_savings',
       'revenue_impact', 'productivity_gain', 'employee_ai_training_hours',
       'ai_maturity_score', 'deployment_count'],
      dtype='str')

In [11]:
df.describe()

,year,ai_adoption_level,ai_investment_usd,automation_rate,cost_savings,revenue_impact,productivity_gain,employee_ai_training_hours,ai_maturity_score,deployment_count
count,200000.000000,200000.000000,2.000000e+05,200000.000000,2.000000e+05,2.000000e+05,200000.000000,200000.000000,200000.000000,200000.000000
mean,2024.991490,0.527774,4.870558e+06,0.436723,2.128918e+06,2.591989e+06,0.395297,76.755334,6.271801,26.337350
std,6.051632,0.256470,3.679704e+06,0.217031,2.415689e+06,3.972751e+06,0.195623,40.046317,1.930643,11.853256
min,2015.000000,0.010000,4.788800e+04,0.000000,4.649000e+03,-1.437676e+07,-0.050000,1.000000,1.000000,3.000000
25%,2020.000000,0.334400,2.221252e+06,0.273500,5.993548e+05,5.339805e+05,0.249300,46.500000,4.730000,16.000000
50%,2025.000000,0.528600,3.991640e+06,0.428150,1.354826e+06,1.408779e+06,0.392600,75.400000,6.280000,25.000000
75%,2030.000000,0.725000,6.517931e+06,0.592000,2.745080e+06,3.132148e+06,0.539300,105.900000,7.830000,36.000000
max,2035.000000,1.000000,5.417034e+07,0.950000,4.433124e+07,1.294787e+08,0.940300,197.900000,10.000000,58.000000

In [12]:
df.columns

Index(['company_id', 'industry', 'country', 'year', 'ai_adoption_level',
       'ai_investment_usd', 'automation_rate', 'cost_savings',
       'revenue_impact', 'productivity_gain', 'employee_ai_training_hours',
       'ai_maturity_score', 'deployment_count'],
      dtype='str')

In [13]:
df.describe

<bound method NDFrame.describe of         company_id            industry         country  year  \
0       CORP-06613  Financial Services           China  2029
1       CORP-01597         Agriculture         Germany  2032
2       CORP-02938              Energy   United States  2024
3       CORP-05207              Retail         Germany  2021
4       CORP-07489          Technology   United States  2024
...            ...                 ...             ...   ...
199995  CORP-06451              Retail          France  2024
199996  CORP-02714              Retail           China  2028
199997  CORP-05490          Technology  United Kingdom  2033
199998  CORP-07057              Retail     South Korea  2026
199999  CORP-00512       Manufacturing         Germany  2017

        ai_adoption_level  ai_investment_usd  automation_rate  cost_savings  \
0                  0.4987           11747237           0.4119       3519354
1                  0.5213            1267219           0.4580        295244
2                  0.6147            8168951           0.5821       2472329
3                  0.4401            1234261           0.2880        512061
4                  0.1918            5000645           0.1906       2122064
...                   ...                ...              ...           ...
199995             0.5021            2845847           0.3577        482569
199996             0.7652            2780945           0.5400       1951316
199997             0.7979           11920296           0.7327       5195264
199998             0.4446            3224465           0.3313       1201451
199999             0.2183            1222634           0.2480        226150

        revenue_impact  productivity_gain  employee_ai_training_hours  \
0              2751513             0.3924                        76.8
1               304776             0.4639                        83.2
2              5170304             0.4953                       123.1
3              -233448             0.3078                        63.1
4              2110644             0.1910                        29.6
...                ...                ...                         ...
199995         1032193             0.2680                        46.4
199996         1227911             0.5217                        97.9
199997         7405993             0.6604                       112.8
199998         1288569             0.2592                        42.6
199999          164725             0.2149                        40.9

        ai_maturity_score  deployment_count
0                    6.37                29
1                    7.19                37
2                    6.72                26
3                    5.68                21
4                    4.33                16
...                   ...               ...
199995               5.58                23
199996               8.33                35
199997               8.35                40
199998               6.69                26
199999               3.59                12

[200000 rows x 13 columns]>

In [14]:
df.describe()

,year,ai_adoption_level,ai_investment_usd,automation_rate,cost_savings,revenue_impact,productivity_gain,employee_ai_training_hours,ai_maturity_score,deployment_count
count,200000.000000,200000.000000,2.000000e+05,200000.000000,2.000000e+05,2.000000e+05,200000.000000,200000.000000,200000.000000,200000.000000
mean,2024.991490,0.527774,4.870558e+06,0.436723,2.128918e+06,2.591989e+06,0.395297,76.755334,6.271801,26.337350
std,6.051632,0.256470,3.679704e+06,0.217031,2.415689e+06,3.972751e+06,0.195623,40.046317,1.930643,11.853256
min,2015.000000,0.010000,4.788800e+04,0.000000,4.649000e+03,-1.437676e+07,-0.050000,1.000000,1.000000,3.000000
25%,2020.000000,0.334400,2.221252e+06,0.273500,5.993548e+05,5.339805e+05,0.249300,46.500000,4.730000,16.000000
50%,2025.000000,0.528600,3.991640e+06,0.428150,1.354826e+06,1.408779e+06,0.392600,75.400000,6.280000,25.000000
75%,2030.000000,0.725000,6.517931e+06,0.592000,2.745080e+06,3.132148e+06,0.539300,105.900000,7.830000,36.000000
max,2035.000000,1.000000,5.417034e+07,0.950000,4.433124e+07,1.294787e+08,0.940300,197.900000,10.000000,58.000000